import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAppContext } from '../context/AppContext';
import { useNavigate } from 'react-router-dom';
const Menu = () => {
    const { user } = useAppContext();
    const navigate = useNavigate();
    return (_jsxs("div", { className: "menu-body", children: [_jsx("div", { className: "page-title", children: "Main Menu" }), _jsxs("div", { className: "menu-grid", children: [_jsxs("button", { className: "menu-card", onClick: () => navigate('/docchat'), children: [_jsx("div", { className: "menu-card-icon blue", children: _jsxs("svg", { width: "26", height: "26", viewBox: "0 0 24 24", fill: "none", stroke: "#1a5fa8", strokeWidth: "2", children: [_jsx("path", { d: "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" }), _jsx("polyline", { points: "14 2 14 8 20 8" }), _jsx("line", { x1: "16", y1: "13", x2: "8", y2: "13" }), _jsx("line", { x1: "16", y1: "17", x2: "8", y2: "17" }), _jsx("polyline", { points: "10 9 9 9 8 9" })] }) }), _jsxs("div", { className: "menu-card-text", children: [_jsx("h3", { children: "Document Chat" }), _jsx("p", { children: "Chat with plant manuals and documentation by discipline" })] })] }), _jsxs("button", { className: "menu-card", onClick: () => navigate('/topology'), children: [_jsx("div", { className: "menu-card-icon green", children: _jsxs("svg", { width: "26", height: "26", viewBox: "0 0 24 24", fill: "none", stroke: "#1a7a50", strokeWidth: "2", children: [_jsx("circle", { cx: "12", cy: "5", r: "3" }), _jsx("circle", { cx: "5", cy: "19", r: "3" }), _jsx("circle", { cx: "19", cy: "19", r: "3" }), _jsx("line", { x1: "12", y1: "8", x2: "5.5", y2: "16" }), _jsx("line", { x1: "12", y1: "8", x2: "18.5", y2: "16" }), _jsx("line", { x1: "7", y1: "19", x2: "17", y2: "19" })] }) }), _jsxs("div", { className: "menu-card-text", children: [_jsx("h3", { children: "Plant Topology" }), _jsx("p", { children: "View machines and their connections in the plant" })] })] }), user?.role === 'admin' && (_jsxs("button", { className: "menu-card admin-only", onClick: () => navigate('/dashboard'), style: { borderColor: 'rgba(94,61,179,0.3)' }, children: [_jsx("div", { className: "menu-card-icon purple", children: _jsxs("svg", { width: "26", height: "26", viewBox: "0 0 24 24", fill: "none", stroke: "#5e3db3", strokeWidth: "2", children: [_jsx("rect", { x: "3", y: "3", width: "7", height: "7" }), _jsx("rect", { x: "14", y: "3", width: "7", height: "7" }), _jsx("rect", { x: "3", y: "14", width: "7", height: "7" }), _jsx("rect", { x: "14", y: "14", width: "7", height: "7" })] }) }), _jsxs("div", { className: "menu-card-text", children: [_jsxs("h3", { children: ["OT Dashboard ", _jsx("span", { style: { fontSize: '10px', background: 'var(--purple-bg)', color: 'var(--purple)', padding: '2px 6px', borderRadius: '4px', fontWeight: 600, marginLeft: '4px' }, children: "ADMIN" })] }), _jsx("p", { children: "Work orders dashboard \u2014 tickets autom\u00E1ticos, tiempos inicio/cierre, KPIs de mantenimiento" })] })] }))] })] }));
};
export default Menu;
