import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { useAppContext } from '../context/AppContext';
import { showToast } from '../components/Toast';
const Report = () => {
    const navigate = useNavigate();
    const { selectedMachine, sessionStart, debugMessages } = useAppContext();
    const summaryText = debugMessages.filter(m => m.role === 'user').map(m => m.content).join('\n');
    const elapsed = sessionStart ? Math.round((Date.now() - sessionStart) / 60000) : 0;
    return (_jsx("div", { className: "report-body w-full", children: _jsxs("div", { className: "report-card mx-auto", children: [_jsx("h2", { children: "Debug Session Report" }), _jsxs("div", { className: "report-field", children: [_jsx("label", { children: "Machine" }), _jsx("div", { className: "rfield-val", children: selectedMachine || '—' })] }), _jsxs("div", { className: "report-field", children: [_jsx("label", { children: "Session Duration" }), _jsx("div", { className: "rfield-val", children: elapsed > 0 ? `${elapsed} minutes` : 'Active session' })] }), _jsxs("div", { className: "report-field", children: [_jsx("label", { children: "Issue Summary" }), _jsx("textarea", { className: "report-textarea", rows: 4, placeholder: "Describe the issue and resolution...", defaultValue: summaryText })] }), _jsxs("div", { className: "report-field", children: [_jsx("label", { children: "Actions Taken" }), _jsx("textarea", { className: "report-textarea", rows: 3, placeholder: "List actions taken..." })] }), _jsxs("div", { className: "report-field", children: [_jsx("label", { children: "Recommended Preventive Actions" }), _jsx("textarea", { className: "report-textarea", rows: 3, placeholder: "List recommended preventive actions..." })] }), _jsxs("div", { className: "report-field", children: [_jsx("label", { children: "Severity" }), _jsxs("select", { className: "form-select", style: { maxWidth: '200px' }, children: [_jsx("option", { children: "Low" }), _jsx("option", { children: "Medium" }), _jsx("option", { children: "High" }), _jsx("option", { children: "Critical" })] })] }), _jsxs("div", { className: "report-actions mt-4", children: [_jsxs("button", { className: "btn btn-green btn-lg", onClick: () => { showToast('✅ Reporte enviado a repositorio central'); navigate(-1); }, children: [_jsxs("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", children: [_jsx("path", { d: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" }), _jsx("polyline", { points: "7 10 12 15 17 10" }), _jsx("line", { x1: "12", y1: "15", x2: "12", y2: "3" })] }), "Send to Repository"] }), _jsx("button", { className: "btn btn-outline", onClick: () => navigate(-1), children: "Back to Debug" })] })] }) }));
};
export default Report;
